Dev
CAB4EHKO/CourseWork1 pull request #1
Opened 2023-03-24 11:19 UTC by CAB4EHKO

Проверьте курсовую

2023-03-24 13:37 UTC, isavinov requested changes

2023-03-24 13:37 UTC, isavinov commented on src/Employee.java
> +    public static void printAllEmployeeData(Employee[] employees) {
Все статические метода для базовой и повышенной сложности, должны быть в классе Main. В классе Employee только храним данные

2023-03-25 07:24 UTC, CAB4EHKO commented on src/Employee.java
> +    public static void printAllEmployeeData(Employee[] employees) {
Исправил)

2023-03-25 15:45 UTC, isavinov approved these changes

2023-04-05 19:01 UTC, merged